package:
  name: rachis
  version: {{ PLUGIN_VERSION }}
source:
  path: ..
build:
  script: make install
requirements:
  host:
  - python {{ python }}
  - pip
  - setuptools
  - versioningit
  - wheel
  run:
  - python {{ python }}
  - pyyaml
  - pandas {{ pandas }}
  - tzlocal {{ tzlocal }}
  - python-dateutil
  - bibtexparser
  - networkx {{ networkx }}
  - dill
  - psutil
  - flufl.lock
  - parsl {{ parsl }}
  - platformdirs
  - tomlkit
  - lxml
  build:
  - python {{ python }}
  - setuptools
  - versioningit
test:
  requires:
  - pytest
  - tornado
  - notebook
  imports:
  - rachis
  commands:
  - QIIMETEST= python -c "import rachis.plugins.dummy_plugin"
  - QIIMETEST= py.test --pyargs --doctest-modules rachis
about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
