#!/usr/bin/env python

import click

from qiime.q2d3.server import start_server

@click.group()
def cli():
    pass

@cli.command("serve")
def serve():
    start_server()

if __name__ == "__main__":
    cli()
