{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}

package:
  name: qiime2
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - pyyaml
    - decorator >=4,<5
    - pandas {{ pandas }}
    # tzlocal 3 is currently broken - once this is fixed drop pin
    - tzlocal <3
    - python-dateutil
    - bibtexparser
    - networkx
    - dill
    - psutil
    - flufl.lock
    - parsl
    - appdirs
    - tomlkit

test:
  requires:
    - pytest
    - tornado
    - notebook

  imports:
    - qiime2

  commands:
    # TODO don't require devs to remember setting this env var before running
    # tests. The value can be anything.
    - QIIMETEST= python -c "import qiime2.plugins.dummy_plugin"

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
