# TODO review meta.yml spec and fill in missing fields as necessary (e.g. build number).

{% set data = load_setup_py_data() %}

package:
  name: qiime2
  version: {{ data.get('version') }}

source:
  path: ../..

build:
  script: python setup.py install

requirements:
  build:
    - python 3.5*
    - setuptools
    - pyyaml
    - decorator
    - pandas
    - tzlocal
    - python-dateutil

  run:
    - python 3.5*
    - setuptools
    - pyyaml
    - decorator
    - pandas
    - tzlocal
    - python-dateutil

test:
  imports:
    - qiime2

  commands:
    # TODO don't require devs to remember setting this env var before running
    # tests. The value can be anything.
    - QIIMETEST= python -c "import qiime2.plugins.dummy_plugin"

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
