name: Increment Release

on:
  push:
    branches:
      - 'Release-*'

jobs:
  increment_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        shell: bash
        run: |
          git config --global user.name "q2d2"
          git config --global user.email "q2d2.noreply@gmail.com"
          IFS='-' read -r _ release <<< $(git branch)
          echo "release=$release" >> $GITHUB_ENV
          echo "default_tag=$release.-1" >> $GITHUB_ENV

      - name: Get last tag
        id: get_last_tag
        shell: bash
        run: |
          last_tag=$(git describe --abbrev=0 --tags 2>/dev/null || echo ${{ env.default_tag }})
          echo "last_tag=$last_tag" >> "$GITHUB_ENV"

      - name: Increment tag
        id: increment_tag
        shell: bash
        run: |
          last_tag=${{ env.last_tag }}
          IFS='.' read -r major minor patch <<< "$last_tag"
          incremented_tag="$major.$minor.$((patch + 1))"
          echo "incremented_tag=$incremented_tag" >> "$GITHUB_ENV"

      - name: Create new tag
        shell: bash
        run: |
          git tag -a ${{ env.incremented_tag }} -m "${{ env.incremented_tag }}"
          git push --follow-tags